### ISSUE TITLE
Request for a command

### ISSUE THREAD

**Issue by bodyboarder2528** [TorchAPI/Essentials#143]
a command that deletes a character entity instead of having to go into the game and do it though the entity list.

**Comment by mccorkle** [comment]
@bodyboarder2528 I think this is old, but just in case -- have you checked out `!identity clean` and `!identity purge` in essentials?  https://wiki.torchapi.net/index.php/Plugins/Essentials#Admin_Commands

**Comment by kontu** [comment]
mccorkle That's not what they want.
They want to delete the actual character entity in game - nothing to do with the sandbox.sbc or the identity. There are several bugs that require a "body delete" of a player to correct when a player is stuck in spectator cam / etc; where you log in game and delete the actual entity of their character body. Deleting from the TorchUI doesn't generally work for it either

**Comment by mccorkle** [comment]
Can either of you describe how to recreate the bug? 

The sandbox files (sbs and sbcs) are the serialized state of the entire universe, so I'm certain whatever the edge case is, it can be cleaned up in the save file offline.

With that said, I can totally see the want for doing that online without having to take the server down and cleaning the potentially giant xml files by hand.  

So, if we can identify what part of the serialized data that is fubared, it is pretty strait forward to write a method in c# to clean it up -- and then we just send Rexxar and Jimmacle a PR :-)

**Comment by LordTylus** [comment]
Actually you dont need the save file for that at all and it is not even useful anyway.

There are often cases where a character is in the world, but dead and doesnt despawn, or alife but the client thinks its dead so people cannot respawn and stuff like that.

So the idea to have them deleted I totally understand and thoeretically there already is code for it however 

https://github.com/TorchAPI/Essentials/blob/e77f39df94611d5f26470770f852a3eeb6ac2e39/Essentials/Commands/EntityModule.cs#L128-L132

the EntityModule in the delete method has a protection for you to not delete characters.

Reason for that being that deleting a character of a currently connected player may mess a lot of stuff up because character being deleted is not equal to character being dead, and not synced as such so it may mess up the client even more. Which may cause you to be stuck in specator cam or something like that.

There once was a big bug where when a ship was deleted it took all characters which were seated inside the ship with it without ejecting them first.

Most of the time it should be enough to just kill the character with !entities kill which then should just get rid of them and if the player reconnects hopefully have them spawn again.

Additionally the code that checks could be altered that you cannot delete a character of an online player but can delete of an offline player.

**Comment by bodyboarder2528** [comment]
The original reason for this request was that im not always in game to delete characters but i have access to console via SEDB

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
